module.exports = {
  purge: {},
  darkMode: false,
  theme: {
    screens: {
      sm: "768px",
      md: "960px",
      lg: "1320px",
    },
    container: {
      padding: "10px",
      center: true,
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",

      black: "#2B2A2A",
      white: "#ffffff",

      primary: "#F56565",
      secondary: "#3A001E",

      red: "#EC2027",
      pink: "#E29C8F",
      pinkLight: "#FFE5DB",
      greenLight: "#C7DCCE",
      blueLight: "#EDF6F9",
      blue: "#A5DCED",
      grayDark: "#707070",
      gray: "#999999",
      grayLight: "#DDDDDD",
    },
    spacing: {
      intro_lg: "600px",
      intro_sm: "350px",
      col: "5px",
      spacer: "10px",
      half: "50%",
      px: "1px",
      0: "0px",
      0.5: "0.125rem",
      1: "0.25rem",
      1.5: "0.375rem",
      2: "0.5rem",
      2.5: "0.625rem",
      3: "0.75rem",
      3.5: "0.875rem",
      4: "1rem",
      5: "1.25rem",
      6: "1.5rem",
      7: "1.75rem",
      8: "2rem",
      9: "2.25rem",
      10: "2.5rem",
      11: "2.75rem",
      12: "3rem",
      14: "3.5rem",
      16: "4rem",
      20: "5rem",
      24: "5.5rem",
      28: "7rem",
      32: "8rem",
      36: "9rem",
      40: "10rem",
      44: "11rem",
      48: "12rem",
      52: "13rem",
      56: "14rem",
      60: "15rem",
      64: "16rem",
      72: "18rem",
      80: "20rem",
      96: "24rem",
    },
    fontFamily: {
      sans: ["'Montserrat'", "sans-serif"],
    },
    fontSize: {
      xxs: ["0.5rem", { lineHeight: "0.75rem" }],
      xs: ["0.75rem", { lineHeight: "1rem" }],
      sm: ["0.875rem", { lineHeight: "1.25rem" }],
      base: ["1rem", { lineHeight: "1.5rem" }],
      lg: ["1.125rem", { lineHeight: "1.75rem" }],
      xl: ["1.25rem", { lineHeight: "1.75rem" }],
      "2xl": ["1.5rem", { lineHeight: "2rem" }],
      "3xl": ["2rem", { lineHeight: "2.25rem" }],
      "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
      "5xl": ["3rem", { lineHeight: "1" }],
      "6xl": ["3.75rem", { lineHeight: "1" }],
      "7xl": ["4.5rem", { lineHeight: "1" }],
      "8xl": ["6rem", { lineHeight: "1" }],
      "9xl": ["8rem", { lineHeight: "1" }],
    },
    fontWeight: {
      normal: "400",
      medium: "500",
      semi: "600",
      bold: "700",
    },
  },
  variantOrder: [
    "first",
    "last",
    "odd",
    "even",
    "visited",
    "checked",
    "empty",
    "read-only",
    "group-hover",
    "group-focus",
    "focus-within",
    "hover",
    "focus",
    "focus-visible",
    "active",
    "disabled",
  ],
  variants: {
    extend: {
      borderWidth: ["responsive", "first", "last"],
      margin: ["responsive", "first", "last"],
      padding: ["responsive", "first", "last"],
    },
  },
  corePlugins: {
    float: false,
    gradientColorStops: false,
    gridAutoRows: false,
    gridColumn: false,
    gridColumnEnd: false,
    gridColumnStart: false,
    gridRow: false,
    gridRowStart: false,
    gridRowEnd: false,
    gridTemplateColumns: false,
    gridTemplateRows: false,
    gridAutoColumns: false,
  },
};
